### ISSUE TITLE
`predict` method auto-differentiation with Zygote.jl

### ISSUE THREAD

**Issue by MarkArdman** [navimakarov/LaplaceRedux.jl#2]
### User story:
- User must be able to use the predict method with differentiation through Zygote.jl

### Subtasks:
- [x] Test if perdict method is auto-differentiable by using [LaplaceReduxModel](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl/blob/main/src/models/differentiable/laplace_redux.jl) with [CounterfactualExplanations.jl](https://github.com/JuliaTrustworthyAI/CounterfactualExplanations.jl)
- [x] Directly auto-differentiate the `predict` function
- [x] Document the issue if it exists
- [x] Determine the root cause and fix it if possible

**Comment by MarkArdman** [comment]
The issue is determined to be with the [`jacobians`](https://github.com/navimakarov/LaplaceRedux.jl/blob/main/src/curvature/functions.jl) method, the call to jacobian method from the Zygote library is by itself not auto-differentiable by Zygote as mentioned in this [issue](https://github.com/FluxML/Zygote.jl/issues/953).

**Comment by MarkArdman** [comment]
The issue is being closed due to the fact that the root cause has been discovered and documented, a could-priority issue will be opened for developing a new method for calculating jacobian in place of Zygote.
