### ISSUE TITLE
Block-diagonal Hessian approximations

### ISSUE THREAD

**Issue by MarkArdman** [navimakarov/LaplaceRedux.jl#6]
### User story:
- User must be able to use block-diagonal Hessian approximations

### Subtasks:
- [ ] Implement parameter division into blocks
- [ ] Implement computation of Hessian for the blocks
- [ ] Compute the approximation by combining the block-diagonal into a single approximation
