### ISSUE TITLE
Subnetwork Laplace

### ISSUE THREAD

**Issue by MarkArdman** [navimakarov/LaplaceRedux.jl#8]
### User story:
- User must be able to use the library’s functionality with only a sample subnetwork weights of the Neural Network

### Subtasks:
- [x] Ensure the model can be utilized with only a sample subnetwork weights of the NN
- [x] Write error handling tests regarding parameter index conversion
- [x] Write tests for the convert indices function
- [x] Test that Laplace constructor correctly calls on the function that converts indices

**Comment by severinbratus** [comment]
Correction: removed sampled, as (randomly) sampling is the subnetwork is not part of (this) feature -- the user selects the weights manually
