### ISSUE TITLE
Add improved documentation for the existing codebase

### ISSUE THREAD

**Issue by Andrei32Ionescu** [navimakarov/LaplaceRedux.jl#9]
### **Subtasks**

- [x] Add improved documentation for curvature/functions.jl
- [x] Add improved documentation for baselaplace.jl
- [x] Add improved documentation for laplace.jl
- [x] Add improved documentation for plotting.jl
- [x] Add improved documentation for utils.jl
